language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

os:
  - linux

sudo: false

install:
  # add brotli for tests
  - pip install brotlipy
  - python setup.py install
  - pip install coverage pytest-cov codecov

script:
  - python setup.py test

after_success:
  - codecov

